# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-toc

# Site settings
encoding: UTF-8
lang: ko # Set the site language
logo: "/assets/logos/favicon-32x32.png"
repo: "https://github.com/kwakky1/kwakky1.github.io"
url: 'https://kwakky1.github.io'
baseurl: ''
title: "Andy's blog"
description: "This is Andy's blog"
permalink: pretty
email: "kwakky1@gmail.com"
google_analytics: "G-VNW35SJF7Z"

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  180: '/assets/logos/apple-touch-icon.png'
  512: '/assets/logos/android-chrome-512x512.png'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

social_links:
  GitHub: https://github.com/kwakky1
  Email: kwakky1@gmail.com

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "무엇이든 기록하자"
    feature_text: |
      손으로 10초면 충분히 할 수 있는 일을 <br> 
      컴퓨터로 하루 종일 프로그래밍해서 자동으로 수행할 때, <br>
      나는 더할 나위 없이 큰 행복을 느낀다.
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      aside: true
      toc: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
